# Generated by Django 4.1.5 on 2023-01-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Título')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('post_content', models.TextField(verbose_name='Conteúdo')),
                ('post_except', models.TextField(verbose_name='Excerto')),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m', verbose_name='Imagem')),
                ('post_pub', models.BooleanField(default=False, verbose_name='Publicado')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Escrito por')),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category', verbose_name='Categoria')),
            ],
        ),
    ]
