# Generated by Django 4.1.5 on 2023-02-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_except',
        ),
    ]
