# Generated by Django 4.1.5 on 2023-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_post_except'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_resume',
            field=models.TextField(default='Digite o resumo da postagem.', verbose_name='Resumo'),
        ),
    ]
