# Generated by Django 4.1.5 on 2023-01-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('commentary', models.TextField(verbose_name='Comentário')),
                ('com_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('com_pub', models.BooleanField(default=False, verbose_name='Publicado')),
                ('com_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post')),
                ('com_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
