# Generated by Django 4.1.5 on 2023-02-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='com_pub',
        ),
    ]
