# Generated by Django 4.1.5 on 2023-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comments_com_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='com_pub',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
